### ISSUE TITLE
No Releases Why

### ISSUE THREAD

**Issue by kannano** [y9neon/SketchwareAPI#2]
Hey Bro where are Releases. Please do provide WiKi Page to how to use this API.

**Comment by y9vad9** [comment]
Hi, I just committed an update for the library: added comments to methods that tell what they do and so on (like, some bug fixes). I also added two tutorials [here](https://github.com/y9neon/SketchwareAPI/tree/master/tutorials).

Later I will add a few more tutorials on how to complete the API and also will [make Java support](https://github.com/y9neon/SketchwareAPI/issues/1).

As for the releases, they are not needed as for me. You can use the library without them.
